//Exercise #1

When a Mule app starts, a connectivity test runs on the components, such as the HTTP or FTP Anypoint Connector, that need to connect to an external server. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app, instead of blocking the deployment.

You can modify this behavior by 1) forcing the deployment to fail when all connection attempts fail, 2) setting a number of reconnection attempts to try after an initial failure, or 3) allowing reconnection attempts to continue as long as the app runs. Here are more details on these three options:

1. Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and any configured reconnection attempts are exhausted.
+
Here is an example that forces the deployment fo fail:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <failsDeployment/> #Option 1
    </reconnection>
  </http:request-connection>
</http:request-config>
----

2. Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. For example, you might set a `count` of `5` reconnection attempts at a `frequency` of every `4000` milliseconds (ms). If not specified, it will default to `2` reconnection attempts at a frequency of every `2000` ms.
+
Here is an example that fails after `5` reconnection attempts with a `4000` ms frequency are exhausted:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <reconnect frequency="4000" count="5"/> #Option 2
    </reconnection>
  </http:request-connection>
</http:request-config>
----

3. Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given `frequency` (for example, every `4000` ms) for as long as the app runs. If not specified, it will default to every `2000` ms. Because there is no limit on the number of retries, no value for `count` is specified.
+
Here is an example that does not set a limit on the number of reconnection attempts and uses a `frequency` of every `4000` ms:
+
[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection>
      <reconnect-forever frequency="4000"/> #Option 3
    </reconnection>
  </http:request-connection>
</http:request-config>
----
